import Head from "next/head";
import Layout from "../components/Layout";

export default function Dictionary() {
  return (
    <div>
      <Head>
        <title>Coffee Harvest Calender</title>
        <meta name="description" content="Generated by create next app"/>
      </Head>
      <Layout>
        <p>Page 1 </p>
      </Layout>
    </div>
  )
}