import Head from 'next/head'
import Layout from "../components/Layout";
import HarvestCalender from "../components/HarvestCalender";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Coffee Harvest Calender</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <HarvestCalender/>
      </Layout>
    </div>
  )
}
