import Head from 'next/head'
import Image from 'next/image'
import Logo from "../components/Logo";
import MonthLine from "../components/MonthLine";
import Layout from "../components/Layout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Coffee Harvest Calender</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex items-center justify-center h-full w-full">
          <div>
            <MonthLine></MonthLine>
            <MonthLine></MonthLine>
            <MonthLine></MonthLine>
          </div>
        </div>
      </Layout>
    </div>
  )
}
